// Eén centrale plek met alle DOM-elementen die de app nodig heeft. Zo
// hoeft geen enkele module zelf document.getElementById te herhalen, en
// zoekt alles in de app z'n knopjes/velden op dezelfde manier op.
export const el = {
  app: document.getElementById("app"),
  configHint: document.getElementById("config-hint"),
  addForm: document.getElementById("add-form"),
  newItem: document.getElementById("new-item"),
  list: document.getElementById("list"),
  emptyHint: document.getElementById("empty-hint"),
  zoekVeld: document.getElementById("zoek-veld"),
  zoekGeenResultaten: document.getElementById("zoek-geen-resultaten"),
  zoekGeenResultatenTerm: document.getElementById("zoek-geen-resultaten-term"),
  syncStatus: document.getElementById("sync-status"),
  statusDot: document.getElementById("status-dot"),
  shareBtn: document.getElementById("share-btn"),
  listCodeBtn: document.getElementById("list-code-btn"),
  listCodeValue: document.getElementById("list-code-value"),
  renameBtn: document.getElementById("rename-btn"),
  listNameEl: document.getElementById("list-name"),
  lockIcon: document.getElementById("list-lock-icon"),
  colorBtn: document.getElementById("color-btn"),
  colorPicker: document.getElementById("color-picker"),
  colorSwatch: document.getElementById("color-swatch"),
  colorResetBtn: document.getElementById("color-reset-btn"),
  nameBtn: document.getElementById("name-btn"),
  badgeKleurHint: document.getElementById("badge-kleur-hint"),
  badgeKleurOpties: document.getElementById("badge-kleur-opties"),
  pushSection: document.getElementById("push-section"),
  pushBtn: document.getElementById("push-btn"),
  listTabs: document.getElementById("list-tabs"),
  listsPanel: document.getElementById("lists-panel"),
  listsCloseBtn: document.getElementById("lists-close-btn"),
  listsPanelList: document.getElementById("lists-panel-list"),
  listsPanelArchivedSection: document.getElementById("lists-panel-archived-section"),
  listsPanelArchived: document.getElementById("lists-panel-archived"),
  listsPanelHiddenSection: document.getElementById("lists-panel-hidden-section"),
  listsPanelHidden: document.getElementById("lists-panel-hidden"),
  listsAddBtn: document.getElementById("lists-add-btn"),
  archiveBtn: document.getElementById("archive-btn"),
  archivePanel: document.getElementById("archive-panel"),
  archiveCloseBtn: document.getElementById("archive-close-btn"),
  archiveList: document.getElementById("archive-list"),
  archiveEmptyHint: document.getElementById("archive-empty-hint"),
  deleteListBtn: document.getElementById("delete-list-btn"),
  settingsBtn: document.getElementById("settings-btn"),
  settingsPanel: document.getElementById("settings-panel"),
  settingsCloseBtn: document.getElementById("settings-close-btn"),
  settingsNameHint: document.getElementById("settings-name-hint"),
  toast: document.getElementById("toast"),
  toastText: document.getElementById("toast-text"),
  toastUndoBtn: document.getElementById("toast-undo-btn"),
  snelToevoegenRij: document.getElementById("snel-toevoegen-rij"),
};
